version: 2

jobs:

  py361:
    working_directory: ~/py361_jarvis
    docker:
      - image: circleci/python:3.6.1
        environment:
          CODACY_PROJECT_TOKEN: "a888117ad27a41ceac9efb3810c5daa5"
          SKIP_INTENSIVE: 1
    steps:
      - checkout

    # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: setup env and run tests
          command: |
            echo "SKIPPING INTENSIVE TESTS? $SKIP_INTENSIVE"
            python3 -m venv test_env
            . test_env/bin/activate
            pip install -q --upgrade pip
            pip install install numpy scipy coverage pytest
            pip install lightgbm
            pip install --quiet -r requirements.txt

            # pip install --quiet -r requirements-optional.txt
            rm -rf jarvis
            # temporarily avoid pip install of matminer
            mkdir jarvis
            cd jarvis
            git clone https://github.com/usnistgov/jarvis.git
            cd jarvis
            pip install --upgrade pip
            cd ../..

            pip install -e .
            pip install -q coverage
            pip install -q codacy-coverage

            git clone https://github.com/knc6/MDCS-api-tools.git
            cd MDCS-api-tools
            python setup.py develop



            coverage run setup.py test
            coverage xml
            #python-codacy-coverage -r coverage.xml
          no_output_timeout: 120m

      - save_cache:
          paths:
          - ./test_env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . test_env/bin/activate
            py.test 

workflows:
  version: 2
  run_tests_on_commit:
    jobs:
      - py361
