version: 2

jobs:

  py361:
    working_directory: ~/py361_jarvis
    docker:
      - image: circleci/python:3.6.1
        environment:
          CODCOV_PROJECT_TOKEN: "b61081a0-39de-44a8-8a9c-97d4be82af6d"
          SKIP_INTENSIVE: 1
    steps:
      - checkout

    # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: setup env and run tests
          command: |
            python3 -m venv test_env
            . test_env/bin/activate
            pip install -q --upgrade pip
            pip install install numpy scipy coverage pytest
            pip install lightgbm
            pip install --quiet -r requirements.txt

            rm -rf jarvis
            mkdir jarvis
            cd jarvis
            git clone https://github.com/knc6/jarvis.git 
            cd jarvis
            pip install --upgrade pip
            cd ../..

            pip install coverage
            pip install codecov

            git clone https://github.com/knc6/MDCS-api-tools.git
            cd MDCS-api-tools
            python setup.py develop
            cd ..


            coverage run setup.py test
            coverage xml
          no_output_timeout: 120m

      - save_cache:
          paths:
          - ./test_env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . test_env/bin/activate
            py.test
            codecov
            codecov --token = "b61081a0-39de-44a8-8a9c-97d4be82af6d" 

workflows:
  version: 2
  run_tests_on_commit:
    jobs:
      - py361
